In [ ]:
import numpy as np
#Basic Array Creation
#create a 1Darray
array_1d=np.array([1,2,3,4,5])
print("1D Array:",array_1d)

1D Array: [1 2 3 4 5]


In [ ]:
#create a 2Darray
array_2D=np.array([[1,2,3],[4,5,6]])
print("2D Array:\n",array_2D)

2D Array:
 [[1 2 3]
 [4 5 6]]


In [ ]:
#create an array with zeros
zeros_array=np.zeros((3,3))
print("Zeros Array:\n",zeros_array)

Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#create an array with ones
ones_array=np.ones((2,2))
print("Ones Array:\n",ones_array)

Ones Array:
 [[1. 1.]
 [1. 1.]]


In [ ]:
#Array Operations
import numpy as np
#create two arrays
a=np.array([1,2,3])
b=np.array([4,5,6])

In [ ]:
#Addition
sum_array=np.add(a,b)
print("Sum:",sum_array)

Sum: [5 7 9]


In [ ]:
#Subtraction
diff_array=np.subtract(a,b)
print("Difference:",diff_array)

Difference: [-3 -3 -3]


In [ ]:
#Multiplication
product_array=np.multiply(a,b)
print("Product:",product_array)

Product: [ 4 10 18]


In [ ]:
#Division
quotient_array=np.divide(a,b)
print("Quotient:",quotient_array)

Quotient: [0.25 0.4  0.5 ]


In [ ]:
#Matrix Multiplication
#create two matrix
matrix_a=np.array([[1,2],[3,4]])
matrix_b=np.array([[5,6],[7,8]])


In [ ]:
#matrix multiplication
matrix_product=np.dot(matrix_a,matrix_b)
print("Matrix Product:\n",matrix_product)

Matrix Product:
 [[19 22]
 [43 50]]


In [ ]:
#Broadcasting
#create an array and a scalar
array=np.array([1,2,3])
scalar=2

#broadcasting
broadcasted_array=array*scalar
print("Broadcasted Array:",broadcasted_array)

Broadcasted Array: [2 4 6]


In [ ]:
#Stastiscal Operations
#create an array
data=np.array([1,2,3,4,5])

#Mean
mean_value=np.mean(data)
print("Mean:",mean_value)

Mean: 3.0


In [ ]:
#Standard deviation
std_value=np.std(data)
print("Standard Deviation:",std_value)

Standard Deviation: 1.4142135623730951


In [ ]:
#Sum
sum_value=np.sum(data)
print("Sum:",sum_value)

Sum: 15


In [ ]:
#Reshaping Array
#create a 1D array
array=np.array([1,2,3,4,5,6])

#Reshape to 2*3
reshaped_array=array.reshape([2,3])
print("Reshaped Array:\n",reshaped_array)

#Reshape to 3*2
reshaped_array=array.reshape([3,2])
print("Reshaped Array:\n",reshaped_array)

Reshaped Array:
 [[1 2 3]
 [4 5 6]]
Reshaped Array:
 [[1 2]
 [3 4]
 [5 6]]


In [ ]:
#Element-wise Operations
import numpy as np
#create two arrays
array_a=np.array([1,2,3])
array_b=np.array([4,5,6])

#Element-wise Operations
add_result=array_a+array_b
print("Element-wise Addition:",add_result)

#Element-wise multiplication
multiply_result=array_a*array_b
print("Element-wise Multiplication:",multiply_result)


Element-wise Addition: [5 7 9]
Element-wise Multiplication: [ 4 10 18]


In [ ]:
#Slicing and Indexing

#create a 2D array
array_2D=np.array([[1,2,3],[4,5,6],[7,8,9]])

#Accessing an element
element=array_2D[1,1]
print("Element at [1,1]:",element)

#Accesing a row
row=array_2D[1,:]
print("Row [1,:]:",row)

#Accessing a column
column=array_2D[:,1]
print("Column [:,1]:",column)



Element at [1,1]: 5
Row [1,:]: [4 5 6]
Column [:,1]: [2 5 8]


In [ ]:
#Creating Random Arrays

#create a random array
random_array=np.random.rand(3,3)
print("Random Integer Array:\n",random_array)

#create a random integer array
random_int_array=np.random.randint(0,10,(3,3))
print("Random Integer Array:\n",random_int_array)

Random Integer Array:
 [[9.57489516e-01 9.47730206e-01 5.82093221e-01]
 [3.22169229e-04 7.78878594e-01 1.89765656e-02]
 [5.12366997e-01 9.35190341e-02 9.20785068e-01]]
Random Integer Array:
 [[0 0 4]
 [9 5 9]
 [5 5 6]]


In [ ]:
#Stacking and Concatenating Arrays

#create two arrays
array_a=np.array([1,2,3])
array_b=np.array([4,5,6])

#Vertical stack
v_stack=np.vstack([array_a,array_b])
print("Vertical Stack:",v_stack)

#Horizontal stack
h_stack=np.hstack([array_a,array_b])
print("Horizontal Stack:",h_stack)

Vertical Stack: [[1 2 3]
 [4 5 6]]
Horizontal Stack: [1 2 3 4 5 6]


In [ ]:
#NUMPY PRACTISE ASSIGNMENT

#BASIC ARRAY CREATION

#create an array with 10 equally spaced no. b/w 0&1
array=np.linspace(0,1,10)
print(array)

#crate a 1D array with 20 random integers b/w 1 and 100
array_int_random=np.random.randint(1,100,20)
print("Random Integer Array:",array_int_random)

#create a 2D array with the shape (4,4)filled with the value 7
array=np.full((4,4),7)
print(array)

#create a 1D array of 10 elements with the same value,3.14
array=np.full(10,3.14)
print(array)

#create a 2D array with the shape (3,3) with values ranging from 1-9
array=np.arange(1,10).reshape(3,3)
print(array)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
Random Integer Array: [49 66 66 56 86 60 69 91 83 79 96 54 98 58 53 52 58 45 13 63]
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
[3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [44]:

#ARRAY OPERATIONS

#create two arrays a=[1,3,5,7,9]and b=[2,4,6,8,10] element-wise substraction
array_a=np.array([1,3,5,7,9])
array_b=np.array([2,4,6,8,10])
diff_array=array_a-array_b
print("Element-wise Substraction:\n",diff_array)

#multiply array a by 3:a=[2,4,6,8]
array_a=np.array([2,4,6,8])
array_a=array_a*3
print("Element-wise multiplication:\n",array_a)

#divide a by 2: a=[10,20,30,40]
array_a=np.array([10,20,30,40])
array_a=array_a/2
print("Element-wise Divide:\n",array_a)

#element-wise modulus of two arrays:a=[5,10,15],b=[2,3,4]
array_a=np.array([5,10,15])
array_b=np.array([2,3,4])
modulus_array=np.mod(array_a,array_b)
print("Element-wise modulus:\n",modulus_array)

#create two arrays:a=[1,2,3],b=[4,5,6] compute the dot product
array_a=([1,2,3])
array_b=([4,5,6])
dot_product_result=np.dot(array_a,array_b)
print("Dot Product:\n",dot_product_result)


Element-wise Substraction:
 [-1 -1 -1 -1 -1]
Element-wise multiplication:
 [ 6 12 18 24]
Element-wise Divide:
 [ 5. 10. 15. 20.]
Element-wise modulus:
 [1 1 3]
Dot Product:
 32


In [43]:
#Matrix MULTIPLICATION
import numpy as np
#create two matrices:a=[[2,3],[4,5]] b=[[1,0],[0,1]] perform matrix multiplication
matrix_a=([[2,3],[4,5]])
matrix_b=([[1,0],[0,1]])
result_matrix=np.dot(matrix_a,matrix_b)
print("Result matrix:\n",result_matrix)

#multiply a 3*3 matrix with 3*1 vector
matrix_a=([[1,2,3],[4,5,6],[7,8,9]])
vector_B=([[10],[20],[30]])
result_vector=np.dot(matrix_a,vector_B)
print("Result matrix:\n",result_vector)

#create a 4*4 identity matrix and multiply it by a 4*4 matrix filled with random integers
identity_matrix=np.eye(4)
random_matrix=np.random.randint(1,10,(4,4))
result_matrix=np.dot(identity_matrix,random_matrix)
print("Identity matrix:\n",identity_matrix)
print("Random matrix:\n",random_matrix)
print("Result matrix:\n",result_matrix)

#matrices a=[[1,2,3].[4,5,6],[7,8,9]] and b=[[9,8,7],[6,5,4],[3,2,1]] compute matrix multiplication
matrix_a=([[1,2,3],[4,5,6],[7,8,9]])
matrix_b=([[9,8,7],[6,5,4],[3,2,1]])
result_matrix=np.dot(matrix_a,matrix_b)
print("Result Matrix:\n",result_matrix)

#create a 2*3 matrix and 3*2 matrix perform matrix multiplication
matrix_a=([[1,2,3],[4,5,6]])
matrix_b=([[7,8],[9,10],[11,12]])
result_matrix=np.dot(matrix_a,matrix_b)
print("Result Matrix:\n",result_matrix)


Result matrix:
 [[2 3]
 [4 5]]
Result matrix:
 [[140]
 [320]
 [500]]
Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Random matrix:
 [[9 9 9 7]
 [9 8 5 1]
 [3 6 3 4]
 [8 4 9 4]]
Result matrix:
 [[9. 9. 9. 7.]
 [9. 8. 5. 1.]
 [3. 6. 3. 4.]
 [8. 4. 9. 4.]]
Result Matrix:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
Result Matrix:
 [[ 58  64]
 [139 154]]


In [45]:
#BROADCASTING

#create a 1D array :a=[10,20,30] sub scalar value 5 using broadcasting
array_a=np.array([10,20,30])
scalar=5
broadcasted_array=array_a-scalar
print("Broadcasted Array:\n",broadcasted_array)

#create a 3*3 array and a 3*1 array add the using broadcasting
array_a=np.array([[1,2,3],[4,5,6],[7,8,9]])
array_b=np.array([[10],[20],[30]])
broadcasted_array=array_a+array_b
print("Broadcasted Array:\n",broadcasted_array)

#divide a 4*4 array by a scalar value,2 using broadcasting
array_a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
scalar=2
broadcasted_array=array_a/2
print("Broadcasted Array:\n",broadcasted_array)

#create a 3*3 array and add 3 to each element using broadcasting
array_a=np.array([[1,2,3],[4,5,6],[7,8,9]])
scalar=3
broadcasted_array=array_a+scalar
print("Broadcasted Array:\n",broadcasted_array)

#multiply a 1D array of shape(5,) by a 2D array of shape(5,5)using broadcasting
array_a=np.array([1,2,3,4,5])
array_b=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
broadcasted_array=array_a[:,np.newaxis]*array_b
print("Broadcasted Array:\n",broadcasted_array)

Broadcasted Array:
 [ 5 15 25]
Broadcasted Array:
 [[11 12 13]
 [24 25 26]
 [37 38 39]]
Broadcasted Array:
 [[0.5 1.  1.5 2. ]
 [2.5 3.  3.5 4. ]
 [4.5 5.  5.5 6. ]
 [6.5 7.  7.5 8. ]]
Broadcasted Array:
 [[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Broadcasted Array:
 [[  1   2   3   4   5]
 [ 12  14  16  18  20]
 [ 33  36  39  42  45]
 [ 64  68  72  76  80]
 [105 110 115 120 125]]


In [46]:
#STATISCAL OPERATIONS

#calculate the median of the array:a=[1,2,3,4,5,6,7,8,9,10]
data=np.array([1,2,3,4,5,6,7,8,9,10])
median_value=np.median(data)
print("Median:\n",median_value)

from scipy import stats
#calculate the mode of the array:a=[1,2,2,3,4,4,4,5,6]
data=np.array([1,2,2,3,4,4,4,5,6])
mode_value=stats.mode(data)
print(mode_value)

#calculate the range of array:a=[10,20,30,40,50]
data=np.array([10,20,30,40,50])
range_value=np.ptp(data)
print("Range:\n",range_value)

#calculate the 25th percentile of the array:a=[1,2,3,4,5,6,7,8,9,10]
data=np.array([1,2,3,4,5,6,7,8,9,10])
percentile_value=np.percentile(data,25)
print("25th Percentile:\n",percentile_value)

#calculate the correlation coefficient b/w two arrays:a=[1,2,3,4,5] and b=[2,4,6,8,10]
data_a=np.array([1,2,3,4,5])
data_b=np.array([2,4,6,8,10])
coeff_value=np.corrcoef(data_a,data_b)
print("Correlation Coefficient:\n",coeff_value)

Median:
 5.5
ModeResult(mode=4, count=3)
Range:
 40
25th Percentile:
 3.25
Correlation Coefficient:
 [[1. 1.]
 [1. 1.]]


In [ ]:
#RESHAPING ARRAYS
import numpy as np
#reshape a 1D array of 12 elements to a 3*4 array
array=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
reshaped_array=array.reshape(3,4)
print("Reshaped Array:\n",reshaped_array)

#reshape a 2D array of shape(6,2) to (3,4)
array=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
reshaped_array=array.reshape(3,4)
print("Reshape Array:\n",reshaped_array)

#create a 4*4 array and flatten it
array_a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
flattened_array=array_a.flatten()
print("Oringinal array:\n",array_a)
print("Flattened Array:\n",flattened_array)

#reshape a 3D array of shape (2,3,4) to (4,3,2)
array=np.arange(24).reshape(2,3,4)
reshaped_array=array.reshape(4,3,2)
print("Original Array:\n",array)
print("Reshaped Array:\n",reshaped_array)

#reshape a 1D array to a 2D array with 1 row and many columns
array=np.array([1,2,3,4,5,6])
reshaped_array=array.reshape(1,-1)
print("Original Array:\n",reshaped_array)


Reshaped Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reshape Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Oringinal array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Flattened Array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
Original Array:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Reshaped Array:
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
Original Array:
 [[1 2 3 4 5 6]]


In [48]:
#Element-wise Operation
import numpy as np
#create two arrays:a=[1,3,5] and b=[2,4,6] perform element-wise division
array_a=np.array([1,3,5])
array_b=np.array([2,4,6])
div_result=array_a/array_b
print("Element-wise Division:",div_result)

#create two arrays:a=[2,4,6] and b=[1,3,5] perform element-wise modulus
array_a=np.array([2,4,6])
array_b=np.array([1,3,5])
mod_result=np.mod(array_a,array_b)
print("Element-wise Modulus:",mod_result)

#add 10 to each element in the array:a=[1,2,3,4,5]
array_a=np.array([1,2,3,4,5])
add_result=array_a+10
print("Addition:\n",add_result)

#subtract 5 from each element in the array:b=[10,20,30,40,50]
array_b=np.array([10,20,30,40,50])
diff_result=array_b-5
print("Subtraction:\n",diff_result)

#square each element in the array:c=[1,2,3,4,5]
array_c=np.array([1,2,3,4,5])
square_result=array_c**2
print("Square:\n",square_result)

Element-wise Division: [0.5        0.75       0.83333333]
Element-wise Modulus: [0 1 1]
Addition:
 [11 12 13 14 15]
Subtraction:
 [ 5 15 25 35 45]
Square:
 [ 1  4  9 16 25]


In [51]:
#SLICING AND INDEXING

#create a 3D array:array_3D=[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]] access the element at[1,1,1]
array_3D=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
element=array_3D[1,1,1]
print("Element at [1,1,1]:",element)

#slice the first layer of a 3D array:array_3D=[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]
array_3D=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
first_layer=array_3D[0]
print("First Layer:\n",first_layer)

#access all elements in the last row of the array:array_2D=[[10,20,30],[40,50,60],[70,80,90]]
array_2D=np.array([[10,20,30],[40,50,60],[70,80,90]])
element=array_2D[-1]
print("Last Row[-1]:\n",element)

#access all elements in the first column of the array:array_2D=[[10,20,30],[40,50,60],[70,80,90]]
array_2D=np.array([[10,20,30],[40,50,60],[70,80,90]])
element=array_2D[:,0]
print("First Column[:,0]:\n",element)

#slice the last two rows and columns of the array:array_2D=[[10,20,30],[40,50,60],[70,80,90]]
array_2D=np.array([[10,20,30],[40,50,60],[70,80,90]])
element=array_2D[-2:,-2:]
print("Last Row and Colums:\n",element)

Element at [1,1,1]: 11
First Layer:
 [[1 2 3]
 [4 5 6]]
Last Row[-1]:
 [70 80 90]
First Column[:,0]:
 [10 40 70]
Last Row and Colums:
 [[50 60]
 [80 90]]


In [32]:
#CREATING RANDOM ARRAYS

#generate a random array of 20 elements with values b/w 0&1
array_random_int=np.random.randint(0,1,20)
print("Random Array:\n",array_random_int)

#create a 4*4 array with random integers b/w 10&20
array_random_int=np.random.randint(10,20,(4,4))
print("Random Array:\n",array_random_int)

#create a 3*3 array with random floats b/w -1&1
lower_bound=-1
upper_bound=1
array_random=np.random.rand(3,3)*(upper_bound-lower_bound)+lower_bound
print("Random Array:\n",array_random)

#generate an array of 15 random integers b/w 100&200
array_random_int=np.random.randint(100,200,15)
print("Random Array:\n",array_random_int)

#create a 5*5 array with random floats b/w 0&10
lower_bound=0
upper_bound=10
array_random=np.random.rand(5,5)*(upper_bound-lower_bound)+lower_bound
print("Random Array:",array_random)

Random Array: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Random Array: [[16 14 11 15]
 [13 18 18 15]
 [14 14 18 15]
 [14 11 15 19]]
Random Array: [[-0.00588055 -0.13928383 -0.86258566]
 [-0.37546009  0.55564411 -0.61814637]
 [ 0.44278096 -0.14398343  0.0415962 ]]
Random Array: [183 196 119 134 197 121 140 111 132 133 116 147 136 123 190]
Random Array: [[2.95352616 9.83764288 7.24054657 8.87087037 9.34144985]
 [6.84729743 2.69853515 4.96133635 1.84011017 4.32912621]
 [2.72610831 2.86039161 5.00178766 9.88827859 9.77874488]
 [2.24982497 5.71781086 0.73554476 3.75525462 8.92887758]
 [0.43219563 6.1667838  2.97880187 4.0131764  4.79675305]]


In [40]:
#STACKING AND CONCATRNATING ARRAYS

#vertically stack two arrays:a=[[1,2],[3,4]] and b=[[5,6],[7,8]]
array_a=([[1,2],[3,4]])
array_b=([[5,6],[7,8]])
v_stack=np.vstack([array_a,array_b])
print("Vertically stack:\n",v_stack)

#horizontally stack two arrays
array_a=([[1,2],[3,4]])
array_b=([[5,6],[7,8]])
h_stack=np.hstack([array_a,array_b])
print("Horizontrally Stack:\n",h_stack)

#concatenate two 1D arrays
array_a=np.array([1,2,3])
array_b=np.array([4,5,6])
concatenated_array=np.concatenate((array_a,array_b))
print("Concatenated Array:\n",concatenated_array)

#concatenated two 3*3 arrays along rows
array_a=np.array([[1,2,3],[4,5,6],[7,8,9]])
array_b=np.array([[10,11,12],[13,14,15],[16,17,18]])
concatenated_array=np.concatenate((array_a,array_b),axis=0)
print("Concatenated Arrays:\n",concatenated_array)


#concatenated two 3*3 arrays along columns
array_a=np.array([[1,2,3],[4,5,6],[7,8,9]])
array_b=np.array([[10,11,12],[13,14,15],[16,17,18]])
concatenated_array=np.concatenate((array_a,array_b),axis=1)
print("Concatenated Arrays:\n",concatenated_array)


Vertically stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontrally Stack:
 [[1 2 5 6]
 [3 4 7 8]]
Concatenated Array:
 [1 2 3 4 5 6]
Concatenated Arrays:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
Concatenated Arrays:
 [[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]
